name: "Run Elementary"
author: "Elementary Data"
description: "Monitor your dbt project and be the first to know of data issues."

branding:
  icon: "activity"
  color: "red"

inputs:
  warehouse-type:
    description: The type of your warehouse (snowflake, bigquery, redshift, etc)
    required: true
  adapter-version:
    description: |
      The dbt-adapter version that should be used (1.5.0 for example).
      If not provided, the latest version will be used.
    required: false
  project-dir:
    description: |
      The path to your dbt project dir.
      You should pass this parameter if the dbt project dir is not located in the current directory (normally the 
      repository root) - the EDR command will run with this directory as the working directory.
    required: false
  profiles-yml:
    description: |
      The content of dbt's `profiles.yml` with the `elementary` profile.
      This is optional if you already have a `profiles.yml` in your repository or in ~/.dbt.
      Can be generated by running `dbt run-operation elementary.generate_elementary_cli_profile` within your project.
    required: false
  edr-command:
    description: The command to run, for example `edr monitor --slack-webhook <SECRET_SLACK_WEBHOOK>`.
    required: true
  profile-target:
    description: |
      Target profile used for internal dbt calls.
      If your `edr_command` uses the `--profile-target` or `--project-profile-target` flags,
      please set this attribute to the value of those flags.
    required: false

  bigquery-keyfile:
    description: The content of your BigQuery keyfile.
    required: false
  gcs-keyfile:
    description: The content of your Google service account keyfile, for usage with Google Cloud Storage.
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
